name: Build BackpackEjector Plugin

on: [push]

jobs:
  build:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Build
      shell: pwsh
      run: |
        # 1. Находим проект
        $proj = Get-ChildItem -Filter "BackpackEjector.csproj" -Recurse | Select-Object -First 1
        if (!$proj) { throw "Файл .csproj не найден!" }
        
        # 2. Собираем. Параметры внутри csproj сами направят файл в корень.
        msbuild $proj.FullName /t:Restore /p:Configuration=Release
        msbuild $proj.FullName /p:Configuration=Release

    - name: Upload DLL
      uses: actions/upload-artifact@v4
      with:
        name: BackpackEjector-Release
        # Теперь берем файл прямо из корня репозитория
        path: "BackpackEjector.dll"
